### ISSUE TITLE
Discrepancy in README

### ISSUE THREAD

**Issue by dvn0** [juancarlospaco/biblioteca-guarrilla#1]
It is stated in the README that there are 0 Dependencies, so I thought you should know that libzip is required :)

**Comment by juancarlospaco** [comment]
After build?, are you sure?. :sob:

**Comment by dvn0** [comment]
Yes, after a successful build, I had to install `libzip` in order to run.

**Comment by juancarlospaco** [comment]
As an optional dependency, you also may need WEBP, 
`libwebp` or `webp` or `webp-tools` depending how your Linux distro names the package, 
...but still should work if its not installed, so its kinda optional or soft dependency.
