### ISSUE TITLE
Cannot open: static/css/spectre.min.css and fails

### ISSUE THREAD

**Issue by dvn0** [juancarlospaco/biblioteca-guarrilla#2]
After I run the example command to start the biblioteca, a few lines are printed regarding the objects in my calibre library, and then the program exits with this error:

```
Error: unhandled exception: cannot open: static/css/spectre.min.css [IOError]
```

It was installed using:
`Nim Compiler Version 0.19.2 [Linux: amd64]`

**Comment by juancarlospaco** [comment]
That is explained on the readme (last items)
https://github.com/juancarlospaco/biblioteca-guarrilla#faq

- Fails with `Error: unhandled exception: cannot open: static/css/spectre.min.css [IOError]` ?

Copy over [the `/static/` folder](https://github.com/juancarlospaco/biblioteca-guarrilla/tree/master/src/static/css).

If you know any way to make it easier send pull request!

**Comment by dvn0** [comment]
Thanks, I did not read the README thoroughly enough. I'm still rather new to Nim; would it be possible to include the css into the binary?

**Comment by juancarlospaco** [comment]
Welcome then :grey_exclamation: :smile: 

Yes, would it be possible to include the css into the binary, I just dont have the time.

**Comment by dvn0** [comment]
Okay, thanks! I'm going to look into it, and I'll create another issue to track that when I do. Closing this one.
